# Generated by Django 5.2 on 2026-03-08 21:21

import django.contrib.postgres.fields
import django.db.models.deletion
import incidents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=122, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('search_terms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name_plural': 'Incident Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, validators=[incidents.validators.validate_past_datetime])),
                ('summary', models.TextField()),
                ('police_file_number', models.CharField(blank=True, max_length=16)),
                ('merchandise_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_multiple_person', models.BooleanField(default=False, verbose_name='Multiple People')),
                ('number_persons', models.SmallIntegerField(default=1, verbose_name='Number Persons Involved')),
                ('merchandise_description', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.geography', verbose_name='geography')),
            ],
            options={
                'verbose_name_plural': 'Incident Reports',
            },
        ),
        migrations.CreateModel(
            name='IncidentReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='incidents.incidentcategory')),
                ('incident_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_categories', to='incidents.incidentreport')),
            ],
            options={
                'verbose_name': 'Incident Report Category',
                'verbose_name_plural': 'Incident Report and Categories',
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='categories',
            field=models.ManyToManyField(related_name='incident_report_categories', through='incidents.IncidentReportCategory', to='incidents.incidentcategory'),
        ),
        migrations.AddConstraint(
            model_name='incidentreportcategory',
            constraint=models.UniqueConstraint(fields=('incident_report', 'category'), name='unique_incident_category'),
        ),
    ]
