# Generated by Django 5.2 on 2026-03-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='is_multiple_person',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='number_persons',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='police_file_number',
        ),
    ]
